import { AppDataSource } from "../config/data-source";
import { Worklog } from "../entities/Worklog";
import { Task } from "../entities/Task";
import { WorkflowStage } from "../entities/WorkflowStage";

export class WorklogService {
    private worklogRepo = AppDataSource.getRepository(Worklog);
    private stageRepo = AppDataSource.getRepository(WorkflowStage);

    async createFromTaskCompletion(task: Task, userId?: string): Promise<Worklog> {
        const assigneeId = userId || task.assigneeId;
        if (!assigneeId) {
            throw new Error("Cannot create worklog without assignee");
        }

        let module: string | undefined;
        if (task.stageId) {
            const stage = await this.stageRepo.findOne({ where: { id: task.stageId } });
            module = stage?.settings?.category || stage?.name;
        }

        const hours = task.metadata?.actualHours ?? task.metadata?.estimatedHours ?? 1;
        const today = new Date().toISOString().slice(0, 10);

        const worklog = this.worklogRepo.create({
            userId: assigneeId,
            projectId: task.projectId,
            taskId: task.id,
            workflowId: task.workflowId,
            description: `Completed task: ${task.name}`,
            hours,
            logDate: today,
            autoGenerated: true,
            module,
        });

        return this.worklogRepo.save(worklog);
    }

    async createManual(data: {
        userId: string;
        projectId?: string;
        taskId?: string;
        workflowId?: string;
        description: string;
        hours: number;
        logDate: string;
        module?: string;
    }): Promise<Worklog> {
        const worklog = this.worklogRepo.create({
            ...data,
            autoGenerated: false,
        });
        return this.worklogRepo.save(worklog);
    }

    async getByProject(projectId: string): Promise<Worklog[]> {
        return this.worklogRepo.find({
            where: { projectId },
            relations: ["user", "task"],
            order: { logDate: "DESC", createdAt: "DESC" },
        });
    }

    async getByUser(userId: string): Promise<Worklog[]> {
        return this.worklogRepo.find({
            where: { userId },
            relations: ["project", "task"],
            order: { logDate: "DESC", createdAt: "DESC" },
        });
    }
}

export const worklogService = new WorklogService();
