import { AppDataSource } from "../config/data-source";
import { Worklog } from "../entities/Worklog";
import { Task } from "../entities/Task";
import { WorkflowStage } from "../entities/WorkflowStage";
import { TaskActivity, TaskActivityType } from "../entities/TaskActivity";
import { ApiError } from "../middlewares/errorHandler";

export interface WorklogFilter {
    organizationId?: string;
    departmentId?: string;
    userId?: string;
    projectId?: string;
    from?: string;
    to?: string;
}

export class WorklogService {
    private worklogRepo = AppDataSource.getRepository(Worklog);
    private stageRepo = AppDataSource.getRepository(WorkflowStage);
    private activityRepo = AppDataSource.getRepository(TaskActivity);

    /**
     * Derive hours from first IN_PROGRESS activity → DONE activity timestamps.
     * Falls back to task metadata / startDate / 1h minimum.
     */
    private async deriveHoursFromActivities(task: Task): Promise<number> {
        if (task.metadata?.actualHours != null) {
            return Number(task.metadata.actualHours);
        }

        const activities = await this.activityRepo.find({
            where: { taskId: task.id },
            order: { createdAt: "ASC" },
        });

        let startedAt: Date | undefined = task.startDate;
        let doneAt: Date | undefined = task.completedAt;

        for (const activity of activities) {
            if (!startedAt && activity.type === TaskActivityType.STAGE_CHANGED) {
                const toName = (activity.details?.toStageName || "").toLowerCase();
                // First move into a non-default / in-progress stage
                if (!toName.includes("todo") && !toName.includes("backlog")) {
                    startedAt = activity.createdAt;
                }
            }

            if (
                !doneAt &&
                (activity.type === TaskActivityType.COMPLETED ||
                    (activity.type === TaskActivityType.STAGE_CHANGED &&
                        ((activity.details?.toStageName || "").toLowerCase().includes("done") ||
                            (activity.details?.toStageName || "").toLowerCase().includes("complete"))))
            ) {
                doneAt = activity.createdAt;
            }
        }

        if (!startedAt) {
            startedAt = task.createdAt;
        }
        if (!doneAt) {
            doneAt = new Date();
        }

        const ms = doneAt.getTime() - startedAt.getTime();
        if (ms <= 0) {
            return task.metadata?.estimatedHours ?? 1;
        }

        const hours = Math.round((ms / 3_600_000) * 100) / 100;
        return Math.max(0.25, Math.min(hours, 999));
    }

    async createFromTaskCompletion(task: Task, userId?: string): Promise<Worklog | null> {
        const assigneeId = userId || task.assigneeId;
        if (!assigneeId) {
            return null;
        }

        // Idempotent — one auto worklog per task
        const existing = await this.worklogRepo.findOne({
            where: { taskId: task.id, autoGenerated: true },
        });
        if (existing) return existing;

        let module: string | undefined;
        if (task.stageId) {
            const stage = await this.stageRepo.findOne({ where: { id: task.stageId } });
            module = stage?.settings?.category || stage?.name;
        }

        const hours = await this.deriveHoursFromActivities(task);
        const today = new Date().toISOString().slice(0, 10);

        const worklog = this.worklogRepo.create({
            userId: assigneeId,
            projectId: task.projectId,
            taskId: task.id,
            workflowId: task.workflowId,
            description: `Completed task: ${task.name}`,
            hours,
            logDate: today,
            autoGenerated: true,
            module,
        });

        return this.worklogRepo.save(worklog);
    }

    async createManual(data: {
        userId: string;
        projectId?: string;
        taskId?: string;
        workflowId?: string;
        description: string;
        hours: number;
        logDate: string;
        module?: string;
    }): Promise<Worklog> {
        const worklog = this.worklogRepo.create({
            ...data,
            autoGenerated: false,
        });
        return this.worklogRepo.save(worklog);
    }

    async getByProject(projectId: string): Promise<Worklog[]> {
        return this.worklogRepo.find({
            where: { projectId },
            relations: ["user", "task"],
            order: { logDate: "DESC", createdAt: "DESC" },
        });
    }

    async getByUser(userId: string): Promise<Worklog[]> {
        return this.worklogRepo.find({
            where: { userId },
            relations: ["project", "task"],
            order: { logDate: "DESC", createdAt: "DESC" },
        });
    }

    /**
     * Called from the completion modal — ensures the auto worklog exists,
     * then applies the employee-confirmed hours and "other work" note.
     */
    async confirmCompletion(data: {
        taskId: string;
        userId?: string;
        hours?: number;
        otherWork?: string;
        description?: string;
    }): Promise<Worklog> {
        const task = await AppDataSource.getRepository(Task).findOne({
            where: { id: data.taskId },
        });
        if (!task) {
            throw new ApiError("Task not found", 404);
        }

        let worklog = await this.createFromTaskCompletion(task, data.userId);
        if (!worklog) {
            throw new ApiError("Unable to create worklog: task has no assignee", 400);
        }

        if (data.hours != null) worklog.hours = data.hours;
        if (data.otherWork !== undefined) worklog.otherWork = data.otherWork;
        if (data.description) worklog.description = data.description;
        worklog.confirmed = true;

        return this.worklogRepo.save(worklog);
    }

    /**
     * Owner-only edit of a worklog.
     */
    async updateWorklog(
        id: string,
        data: { hours?: number; description?: string; otherWork?: string },
        requesterId: string
    ): Promise<Worklog> {
        const worklog = await this.worklogRepo.findOne({ where: { id } });
        if (!worklog) {
            throw new ApiError("Worklog not found", 404);
        }
        if (worklog.userId !== requesterId) {
            throw new ApiError("You can only edit your own worklogs", 403);
        }

        if (data.hours != null) worklog.hours = data.hours;
        if (data.description !== undefined) worklog.description = data.description;
        if (data.otherWork !== undefined) worklog.otherWork = data.otherWork;

        return this.worklogRepo.save(worklog);
    }

    /**
     * Management listing scoped by organization/department with optional filters.
     */
    async listForManagement(filter: WorklogFilter): Promise<Worklog[]> {
        const qb = this.worklogRepo
            .createQueryBuilder("worklog")
            .leftJoinAndSelect("worklog.user", "user")
            .leftJoinAndSelect("worklog.project", "project")
            .leftJoinAndSelect("worklog.task", "task")
            .orderBy("worklog.logDate", "DESC")
            .addOrderBy("worklog.createdAt", "DESC");

        if (filter.organizationId) {
            qb.andWhere("user.organizationId = :organizationId", {
                organizationId: filter.organizationId,
            });
        }
        if (filter.departmentId) {
            qb.andWhere("user.departmentId = :departmentId", {
                departmentId: filter.departmentId,
            });
        }
        if (filter.userId) {
            qb.andWhere("worklog.userId = :userId", { userId: filter.userId });
        }
        if (filter.projectId) {
            qb.andWhere("worklog.projectId = :projectId", { projectId: filter.projectId });
        }
        if (filter.from) {
            qb.andWhere("worklog.logDate >= :from", { from: filter.from });
        }
        if (filter.to) {
            qb.andWhere("worklog.logDate <= :to", { to: filter.to });
        }

        return qb.getMany();
    }
}

export const worklogService = new WorklogService();
