import { AppDataSource } from "../config/data-source";
import { Worklog } from "../entities/Worklog";
import { Task } from "../entities/Task";
import { WorkflowStage } from "../entities/WorkflowStage";
import { TaskActivity, TaskActivityType } from "../entities/TaskActivity";

export class WorklogService {
    private worklogRepo = AppDataSource.getRepository(Worklog);
    private stageRepo = AppDataSource.getRepository(WorkflowStage);
    private activityRepo = AppDataSource.getRepository(TaskActivity);

    /**
     * Derive hours from first IN_PROGRESS activity → DONE activity timestamps.
     * Falls back to task metadata / startDate / 1h minimum.
     */
    private async deriveHoursFromActivities(task: Task): Promise<number> {
        if (task.metadata?.actualHours != null) {
            return Number(task.metadata.actualHours);
        }

        const activities = await this.activityRepo.find({
            where: { taskId: task.id },
            order: { createdAt: "ASC" },
        });

        let startedAt: Date | undefined = task.startDate;
        let doneAt: Date | undefined = task.completedAt;

        for (const activity of activities) {
            if (!startedAt && activity.type === TaskActivityType.STAGE_CHANGED) {
                const toName = (activity.details?.toStageName || "").toLowerCase();
                // First move into a non-default / in-progress stage
                if (!toName.includes("todo") && !toName.includes("backlog")) {
                    startedAt = activity.createdAt;
                }
            }

            if (
                !doneAt &&
                (activity.type === TaskActivityType.COMPLETED ||
                    (activity.type === TaskActivityType.STAGE_CHANGED &&
                        ((activity.details?.toStageName || "").toLowerCase().includes("done") ||
                            (activity.details?.toStageName || "").toLowerCase().includes("complete"))))
            ) {
                doneAt = activity.createdAt;
            }
        }

        if (!startedAt) {
            startedAt = task.createdAt;
        }
        if (!doneAt) {
            doneAt = new Date();
        }

        const ms = doneAt.getTime() - startedAt.getTime();
        if (ms <= 0) {
            return task.metadata?.estimatedHours ?? 1;
        }

        const hours = Math.round((ms / 3_600_000) * 100) / 100;
        return Math.max(0.25, Math.min(hours, 999));
    }

    async createFromTaskCompletion(task: Task, userId?: string): Promise<Worklog | null> {
        const assigneeId = userId || task.assigneeId;
        if (!assigneeId) {
            return null;
        }

        // Idempotent — one auto worklog per task
        const existing = await this.worklogRepo.findOne({
            where: { taskId: task.id, autoGenerated: true },
        });
        if (existing) return existing;

        let module: string | undefined;
        if (task.stageId) {
            const stage = await this.stageRepo.findOne({ where: { id: task.stageId } });
            module = stage?.settings?.category || stage?.name;
        }

        const hours = await this.deriveHoursFromActivities(task);
        const today = new Date().toISOString().slice(0, 10);

        const worklog = this.worklogRepo.create({
            userId: assigneeId,
            projectId: task.projectId,
            taskId: task.id,
            workflowId: task.workflowId,
            description: `Completed task: ${task.name}`,
            hours,
            logDate: today,
            autoGenerated: true,
            module,
        });

        return this.worklogRepo.save(worklog);
    }

    async createManual(data: {
        userId: string;
        projectId?: string;
        taskId?: string;
        workflowId?: string;
        description: string;
        hours: number;
        logDate: string;
        module?: string;
    }): Promise<Worklog> {
        const worklog = this.worklogRepo.create({
            ...data,
            autoGenerated: false,
        });
        return this.worklogRepo.save(worklog);
    }

    async getByProject(projectId: string): Promise<Worklog[]> {
        return this.worklogRepo.find({
            where: { projectId },
            relations: ["user", "task"],
            order: { logDate: "DESC", createdAt: "DESC" },
        });
    }

    async getByUser(userId: string): Promise<Worklog[]> {
        return this.worklogRepo.find({
            where: { userId },
            relations: ["project", "task"],
            order: { logDate: "DESC", createdAt: "DESC" },
        });
    }
}

export const worklogService = new WorklogService();
