export enum ProjectPermissionKey {
    PROJECT_VIEW = "PROJECT_VIEW",
    WORKFLOW_BOARD_ACCESS = "WORKFLOW_BOARD_ACCESS",
    KANBAN_BOARD_ACCESS = "KANBAN_BOARD_ACCESS",
    TASK_CREATE = "TASK_CREATE",
    TASK_EDIT = "TASK_EDIT",
    TASK_DELETE = "TASK_DELETE",
    TASK_MOVE = "TASK_MOVE",
    TASK_ASSIGN = "TASK_ASSIGN",
    PROJECT_MEMBER_MANAGE = "PROJECT_MEMBER_MANAGE",
    PROJECT_SETTINGS_MANAGE = "PROJECT_SETTINGS_MANAGE",
    PROJECT_ARCHIVE = "PROJECT_ARCHIVE",
    PROJECT_DELETE = "PROJECT_DELETE"
}

export const ALL_PROJECT_PERMISSIONS: ProjectPermissionKey[] = Object.values(ProjectPermissionKey);
