import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    ManyToOne,
    JoinColumn,
    Index,
} from "typeorm";
import { User } from "./User";
import { Project } from "./Project";
import { Task } from "./Task";
import { Workflow } from "./Workflow";

@Entity("worklogs")
export class Worklog {
    @PrimaryGeneratedColumn("uuid")
    id!: string;

    @ManyToOne(() => User, { onDelete: "CASCADE" })
    @JoinColumn({ name: "userId" })
    user!: User;

    @Column()
    @Index()
    userId!: string;

    @ManyToOne(() => Project, { nullable: true, onDelete: "SET NULL" })
    @JoinColumn({ name: "projectId" })
    project?: Project;

    @Column({ nullable: true })
    @Index()
    projectId?: string;

    @ManyToOne(() => Task, { nullable: true, onDelete: "SET NULL" })
    @JoinColumn({ name: "taskId" })
    task?: Task;

    @Column({ nullable: true })
    @Index()
    taskId?: string;

    @ManyToOne(() => Workflow, { nullable: true, onDelete: "SET NULL" })
    @JoinColumn({ name: "workflowId" })
    workflow?: Workflow;

    @Column({ nullable: true })
    workflowId?: string;

    @Column({ type: "text" })
    description!: string;

    @Column({ type: "decimal", precision: 5, scale: 2, default: 0 })
    hours!: number;

    @Column({ type: "date" })
    logDate!: string;

    @Column({ default: false })
    autoGenerated!: boolean;

    @Column({ type: "text", nullable: true })
    otherWork?: string;

    @Column({ default: false })
    confirmed!: boolean;

    @Column({ nullable: true })
    module?: string;

    @CreateDateColumn()
    createdAt!: Date;
}
