import { Response } from "express";
import ExcelJS from "exceljs";
import { AuthRequest } from "../middlewares/auth";
import { PermissionRequest } from "../middlewares/permission";
import { worklogService, WorklogFilter } from "../services/WorklogService";

export class WorklogController {
    async listByProject(req: AuthRequest, res: Response) {
        try {
            const worklogs = await worklogService.getByProject(String(req.params.projectId));
            res.json({ data: worklogs });
        } catch (err: any) {
            res.status(err.statusCode || 500).json({ message: err.message });
        }
    }

    async listByUser(req: AuthRequest, res: Response) {
        try {
            const userId = (req.query.userId as string) || req.user!.id;
            const worklogs = await worklogService.getByUser(userId);
            res.json({ data: worklogs });
        } catch (err: any) {
            res.status(err.statusCode || 500).json({ message: err.message });
        }
    }

    async create(req: AuthRequest, res: Response) {
        try {
            const worklog = await worklogService.createManual({
                ...req.body,
                userId: req.body.userId || req.user!.id,
            });
            res.status(201).json({ data: worklog });
        } catch (err: any) {
            res.status(err.statusCode || 400).json({ message: err.message });
        }
    }

    async confirmCompletion(req: AuthRequest, res: Response) {
        try {
            const worklog = await worklogService.confirmCompletion({
                taskId: req.body.taskId,
                userId: req.body.userId || req.user!.id,
                hours: req.body.hours,
                otherWork: req.body.otherWork,
                description: req.body.description,
            });
            res.status(201).json({ data: worklog });
        } catch (err: any) {
            res.status(err.statusCode || 400).json({ message: err.message });
        }
    }

    async update(req: AuthRequest, res: Response) {
        try {
            const worklog = await worklogService.updateWorklog(
                String(req.params.id),
                {
                    hours: req.body.hours,
                    description: req.body.description,
                    otherWork: req.body.otherWork,
                },
                req.user!.id
            );
            res.json({ data: worklog });
        } catch (err: any) {
            res.status(err.statusCode || 400).json({ message: err.message });
        }
    }

    async listAll(req: PermissionRequest, res: Response) {
        try {
            const filter = buildFilter(req);
            const worklogs = await worklogService.listForManagement(filter);
            res.json({ data: worklogs });
        } catch (err: any) {
            res.status(err.statusCode || 500).json({ message: err.message });
        }
    }

    async exportExcel(req: PermissionRequest, res: Response) {
        try {
            const filter = buildFilter(req);
            const worklogs = await worklogService.listForManagement(filter);

            const workbook = new ExcelJS.Workbook();
            workbook.creator = "PMS";
            workbook.created = new Date();
            const sheet = workbook.addWorksheet("Worklogs");

            sheet.columns = [
                { header: "Date", key: "logDate", width: 14 },
                { header: "Employee", key: "employee", width: 24 },
                { header: "Email", key: "email", width: 28 },
                { header: "Project", key: "project", width: 24 },
                { header: "Task", key: "task", width: 30 },
                { header: "Description", key: "description", width: 40 },
                { header: "Other Work", key: "otherWork", width: 40 },
                { header: "Hours", key: "hours", width: 10 },
                { header: "Module", key: "module", width: 18 },
                { header: "Source", key: "source", width: 12 },
                { header: "Confirmed", key: "confirmed", width: 12 },
            ];
            sheet.getRow(1).font = { bold: true };

            for (const w of worklogs) {
                sheet.addRow({
                    logDate: w.logDate,
                    employee: w.user?.fullName || "",
                    email: w.user?.email || "",
                    project: w.project?.name || "",
                    task: w.task?.name || "",
                    description: w.description,
                    otherWork: w.otherWork || "",
                    hours: Number(w.hours),
                    module: w.module || "",
                    source: w.autoGenerated ? "Auto" : "Manual",
                    confirmed: w.confirmed ? "Yes" : "No",
                });
            }

            const fileName = `worklogs-${new Date().toISOString().slice(0, 10)}.xlsx`;
            res.setHeader(
                "Content-Type",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            );
            res.setHeader("Content-Disposition", `attachment; filename="${fileName}"`);

            await workbook.xlsx.write(res);
            res.end();
        } catch (err: any) {
            res.status(err.statusCode || 500).json({ message: err.message });
        }
    }
}

/**
 * Build a management filter scoped to the requester's organization/department.
 * Higher-privileged (org/system scope) users see the whole organization;
 * others are constrained to their own department.
 */
function buildFilter(req: PermissionRequest): WorklogFilter {
    const ctx = req.userContext;
    const scopeToDepartment = ctx ? ctx.roleLevel >= RoleLevelDepartmentHead : false;

    return {
        organizationId: ctx?.organizationId,
        departmentId: scopeToDepartment ? ctx?.departmentId : undefined,
        userId: (req.query.userId as string) || undefined,
        projectId: (req.query.projectId as string) || undefined,
        from: (req.query.from as string) || undefined,
        to: (req.query.to as string) || undefined,
    };
}

// RoleLevel.DEPARTMENT_HEAD === 3; managers (4) and department heads see their
// department only, admins and above see the whole organization.
const RoleLevelDepartmentHead = 3;
